Make Emulator class testable
* Moved the Registers and Flags struct definitions out of the class
  definition so that other variables can be created with those types
  (specifically, in tests).
* Moved the switch block from Emulate() to EmulateOpcode()
* Added some getters to the Emulator class for use in tests.
* At the top of test_em.cpp I overloaded the == operator for comparing
  Registers and Flags structs.
* I wrote a few example tests to try things out.
* Build was failing with a "emulator.cpp:162 undefined reference to
  `Disassembler::Disassemble(char*, int)`" error.
  I guess it wasn't linking the disassemble.cpp code with the
  emulator.cpp code. Adding target_link_libraries(Emulator Disassembler)
  to CMakeLists.txt in the emulator folder fixed this, but I doubt that
  is the best solution.